<?php
namespace Modules\Community\Controllers;

use App\Notifications\AdminChannelServices;
use Modules\Booking\Events\BookingUpdatedEvent;
use Modules\Core\Events\CreatedServicesEvent;
use Modules\FrontendController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Modules\Location\Models\LocationCategory;
use Modules\Community\Hook;
use Modules\Community\Models\Community;
use Modules\Community\Models\CommunityCategory;
use Modules\Community\Models\CommunityTranslation;
use Modules\Location\Models\Location;
use Modules\Core\Models\Attributes;
use Modules\Community\Models\CommunityTerm;
use Modules\Booking\Models\Booking;

class ManageCommunityController extends FrontendController
{
    protected $communityClass;
    protected $communityTranslationClass;
    protected $communityCategoryClass;
    protected $communityTermClass;
    protected $attributesClass;
    protected $locationClass;
    protected $bookingClass;
    /**
     * @var string
     */
    private $locationCategoryClass;

    public function __construct()
    {
        $this->communityClass = Community::class;
        $this->communityTranslationClass = CommunityTranslation::class;
        $this->communityCategoryClass = CommunityCategory::class;
        $this->communityTermClass = CommunityTerm::class;
        $this->attributesClass = Attributes::class;
        $this->locationClass = Location::class;
        $this->locationCategoryClass = LocationCategory::class;
        $this->bookingClass = Booking::class;
        parent::__construct();
    }

    public function callAction($method, $parameters)
    {
        if (setting_item('community_disable')) {
            return redirect('/');
        }
        return parent::callAction($method, $parameters); // TODO: Change the autogenerated stub
    }

    public function manageCommunity(Request $request)
    {
        $this->checkPermission('community_view');
        $user_id = Auth::id();
        $list_community = $this->communityClass::where("create_user", $user_id)->orderBy('id', 'desc');
        $data = [
            'rows'        => $list_community->paginate(5),
            'breadcrumbs' => [
                [
                    'name' => __('Manage Communitys'),
                    'url'  => route('community.vendor.index'),
                ],
                [
                    'name'  => __('All'),
                    'class' => 'active'
                ],
            ],
            'page_title'  => __("Manage Communitys"),
        ];
        return view('Community::frontend.manageCommunity.index', $data);
    }

    public function recovery(Request $request)
    {
        $this->checkPermission('community_view');
        $user_id = Auth::id();
        $list_community = $this->communityClass::onlyTrashed()->where("create_user", $user_id)->orderBy('id', 'desc');
        $data = [
            'rows'        => $list_community->paginate(5),
            'recovery'           => 1,
            'breadcrumbs' => [
                [
                    'name' => __('Manage Communitys'),
                    'url'  => route('community.vendor.index'),
                ],
                [
                    'name'  => __('Recovery'),
                    'class' => 'active'
                ],
            ],
            'page_title'  => __("Recovery Communitys"),
        ];
        return view('Community::frontend.manageCommunity.index', $data);
    }

    public function restore($id)
    {
        $this->checkPermission('community_delete');
        $user_id = Auth::id();
        $query = $this->communityClass::onlyTrashed()->where("create_user", $user_id)->where("id", $id)->first();
        if(!empty($query)){
            $query->restore();
        }
        return redirect(route('community.vendor.recovery'))->with('success', __('Restore community success!'));
    }

    public function createCommunity(Request $request)
    {
        $this->checkPermission('community_create');
        $row = new $this->communityClass();
        $data = [
            'row'           => $row,
            'translation'   => new $this->communityTranslationClass(),
            'community_category' => $this->communityCategoryClass::get()->toTree(),
            'community_location' => $this->locationClass::where("status", "publish")->get()->toTree(),
            'attributes'    => $this->attributesClass::where('service', 'community')->get(),
            'location_category'=>$this->locationCategoryClass::where("status", "publish")->get(),

            'breadcrumbs'   => [
                [
                    'name' => __('Manage Communitys'),
                    'url'  => route('community.vendor.index'),
                ],
                [
                    'name'  => __('Create'),
                    'class' => 'active'
                ],
            ],
            'page_title'    => __("Create Communitys"),
        ];
        return view('Community::frontend.manageCommunity.detail', $data);
    }

    public function editCommunity(Request $request, $id)
    {
        $this->checkPermission('community_update');
        $user_id = Auth::id();
        $row = $this->communityClass::where("create_user", $user_id);
        $row = $row->find($id);
        if (empty($row)) {
            return redirect(route('community.vendor.index'))->with('warning', __('Community not found!'));
        }
        $translation = $row->translateOrOrigin($request->query('lang'));
        $data = [
            'translation'    => $translation,
            'row'            => $row,
            'community_category'  => $this->communityCategoryClass::where("status", "publish")->get()->toTree(),
            'community_location'  => $this->locationClass::where("status", "publish")->get()->toTree(),
            'location_category'=>$this->locationCategoryClass::where("status", "publish")->get(),
            'attributes'     => $this->attributesClass::where('service', 'community')->get(),
            "selected_terms" => $row->community_term->pluck('term_id'),
            'breadcrumbs'    => [
                [
                    'name' => __('Manage Communitys'),
                    'url'  => route('community.vendor.index'),
                ],
                [
                    'name'  => __('Edit'),
                    'class' => 'active'
                ],
            ],
            'page_title'     => __("Edit Communitys"),
        ];
        return view('Community::frontend.manageCommunity.detail', $data);
    }

    public function store(Request $request, $id)
    {
        if ($id > 0) {
            $this->checkPermission('community_update');
            $row = $this->communityClass::find($id);
            if (empty($row)) {
                return redirect(route('community.vendor.edit', ['id' => $row->id]));
            }
            if ($row->create_user != Auth::id() and !$this->hasPermission('community_manage_others')) {
                return redirect(route('community.vendor.edit', ['id' => $row->id]));
            }
        } else {
            $this->checkPermission('community_create');
            $row = new $this->communityClass();
            $row->status = "publish";
            if (setting_item("community_vendor_create_service_must_approved_by_admin", 0)) {
                $row->status = "pending";
            }
        }
        $row->fillByAttr([
            'title',
            'content',
            'image_id',
            'banner_image_id',
            'short_desc',
            'category_id',
            'location_id',
            'address',
            'map_lat',
            'map_lng',
            'map_zoom',
            'gallery',
            'video',
            'default_state',
            'price',
            'sale_price',
            'duration',
            'max_people',
            'min_people',
            'faqs',
            'include',
            'exclude',
            'itinerary',
            'enable_service_fee',
            'service_fee',
            'surrounding',
            'min_day_before_booking',
            'enable_fixed_date',
            'start_date',
            'end_date',
            'last_booking_date',

        ], $request->input());

        if(!auth()->user()->checkUserPlan() and $row->status == "publish") {
            return redirect(route('user.plan'));
        }
        $row->ical_import_url = $request->ical_import_url;
        $res = $row->saveOriginOrTranslation($request->input('lang'), true);
        if ($res) {
            if (!$request->input('lang') or is_default_lang($request->input('lang'))) {
                $this->saveTerms($row, $request);
                $row->saveMeta($request);
            }
            do_action(Hook::AFTER_SAVING,$row,$request);
            if ($id > 0) {
                return back()->with('success', __('Community updated'));
            } else {
                event(new CreatedServicesEvent($row));
                return redirect(route('community.vendor.edit', ['id' => $row->id]))->with('success', __('Community created'));
            }
        }
    }

    public function saveTerms($row, $request)
    {
        if (empty($request->input('terms'))) {
            $this->communityTermClass::where('community_id', $row->id)->delete();
        } else {
            $term_ids = $request->input('terms');
            foreach ($term_ids as $term_id) {
                $this->communityTermClass::firstOrCreate([
                    'term_id' => $term_id,
                    'community_id' => $row->id
                ]);
            }
            $this->communityTermClass::where('community_id', $row->id)->whereNotIn('term_id', $term_ids)->delete();
        }
    }

    public function deleteCommunity($id)
    {
        $this->checkPermission('community_delete');
        $user_id = Auth::id();
        if(\request()->query('permanently_delete')){
            $query = $this->communityClass::where("create_user", $user_id)->where("id", $id)->withTrashed()->first();
            if (!empty($query)) {
                $query->forceDelete();
            }
        }else {
            $query = $this->communityClass::where("create_user", $user_id)->where("id", $id)->first();
            if (!empty($query)) {
                $query->delete();
            }
        }
        return redirect(route('community.vendor.index'))->with('success', __('Delete community success!'));
    }

    public function bulkEditCommunity($id, Request $request)
    {
        $this->checkPermission('community_update');
        $action = $request->input('action');
        $user_id = Auth::id();
        $query = $this->communityClass::where("create_user", $user_id)->where("id", $id)->first();
        if (empty($id)) {
            return redirect()->back()->with('error', __('No item!'));
        }
        if (empty($action)) {
            return redirect()->back()->with('error', __('Please select an action!'));
        }
        if (empty($query)) {
            return redirect()->back()->with('error', __('Not Found'));
        }
        switch ($action) {
            case "make-hide":
                $query->status = "draft";
                break;
            case "make-publish":
                $query->status = "publish";
                if(!auth()->user()->checkUserPlan() ) {
                    return redirect(route('user.plan'));
                }
                break;
        }
        $query->save();
        return redirect()->back()->with('success', __('Update success!'));
    }

    public function bookingReportBulkEdit($booking_id, Request $request)
    {
        $status = $request->input('status');
        if (!empty(setting_item("community_allow_vendor_can_change_their_booking_status")) and !empty($status) and !empty($booking_id)) {
            $query = $this->bookingClass::where("id", $booking_id);
            $query->where("vendor_id", Auth::id());
            $item = $query->first();
            if (!empty($item)) {
                $item->status = $status;
                $item->save();

                if($status == Booking::CANCELLED) $item->tryRefundToWallet();

                event(new BookingUpdatedEvent($item));
                return redirect()->back()->with('success', __('Update success'));
            }
            return redirect()->back()->with('error', __('Booking not found!'));
        }
        return redirect()->back()->with('error', __('Update fail!'));
    }

    public function cloneCommunity(Request $request, $id)
    {
        $this->checkPermission('community_update');
        $user_id = Auth::id();
        $row = $this->communityClass::where("create_user", $user_id);
        $row = $row->find($id);
        if (empty($row)) {
            return redirect(route('community.vendor.index'))->with('warning', __('Community not found!'));
        };
        try {
            $clone = $row->replicate();
            $clone->status = 'draft';
            $clone->push();
            if (!empty($row->community_term)) {
                foreach ($row->community_term as $term) {
                    $e = $term->replicate();
                    if ($e->push()) {
                        $clone->community_term()->save($e);
                    }
                }
            }
            if (!empty($row->meta)) {
                $e = $row->meta->replicate();
                if ($e->push()) {
                    $clone->meta()->save($e);
                }
            }
            if (!empty($row->translations)) {
                foreach ($row->translations as $translation) {
                    $e = $translation->replicate();
                    $e->origin_id = $clone->id;
                    if ($e->push()) {
                        $clone->translations()->save($e);
                    }
                }
            }
            return redirect()->back()->with('success', __('Community clone was successful'));
        } catch (\Exception $exception) {
            $clone->delete();
            return redirect()->back()->with('warning', __($exception->getMessage()));
        }
    }
}
